[package]
name = "KnightAge"
version = "0.1.0"
edition = "2021"
authors = ["Arriety"]

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
rand = "0.8"
thiserror = "1"
async-trait = "0.1"
num_cpus = "1.16"
